# Generated by Django 3.0.8 on 2020-07-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200715_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recherche',
            name='demarrage_officiel',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='premiere_lecture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
