# Generated by Django 3.0.8 on 2020-07-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20200715_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujet',
            name='correction',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='commentaires',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sujet',
            name='explications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sujet',
            name='lien',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
