# Generated by Django 3.0.8 on 2020-07-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20200717_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='discord_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
