# Generated by Django 3.0.8 on 2020-07-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_candidat_discord_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='classe',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='login',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='nom',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='prenom',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
