# Generated by Django 3.0.8 on 2020-07-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20200719_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='classe',
        ),
        migrations.AddField(
            model_name='candidat',
            name='annee_bac',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
