# Generated by Django 3.0.8 on 2020-07-20 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20200720_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recherche',
            name='candidat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Candidat'),
        ),
    ]
