# Generated by Django 3.0.8 on 2020-07-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20200720_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='code',
            field=models.CharField(default='G', max_length=256),
            preserve_default=False,
        ),
    ]
