# Generated by Django 3.1.2 on 2020-10-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_parcours_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='recherche',
            name='debut_pause',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recherche',
            name='faux_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
